_data:
  host: localhost
  port: 5000
  default_domain_id: id
  default_domain_name: name
  domain_id: id
  domain_name: name
  password: password
  project_domain_name: name
  project_id: id
  project_name: name
  tenant_id: id
  tenant_name: name
  user_domain_name: name
  user_id: id
  user: user
  version: v1
  barbican_endpoint: 'http://localhost:9311/'
  barbican_endpoint_type: public
